version: '3.5'

services:
    mariadb:
      build: mariadb/
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: moodle
        MYSQL_USER: moodle
        MYSQL_PASSWORD: moodle

    moodle:
      build:
        context: moodle/
      environment:
        MOODLE_DOMAIN: localhost.test
        MOODLE_DB_HOST: mariadb
        MYSQL_PORT_3306_TCP: 3306
        MOODLE_DB_NAME: moodle
        MOODLE_DB_USER: moodle
        MOODLE_DB_PASSWORD: moodle
      restart: unless-stopped
      depends_on:
        - mariadb
      links:
        - mariadb

    nginx:
      build: nginx/
      depends_on:
        - moodle
      ports:
        - 8080:80
      volumes:
        - /moodle/src:/var/www/html
      restart: unless-stopped
